### ISSUE TITLE
Repetition in Capy of the hour

### ISSUE THREAD

**Issue by emilio-aburto** [Looskie/capybara-api#4]
The capys of the hours repeat a lot. Seems like the culprit may be the way the index is chosen. I can't provide a Pull request right now, maybe in a couple of weeks. 

Thanks a lot for the API btw!

https://github.com/Looskie/capybara-api/blob/cae33ea4e410e523b9a9a16a41f8a2f7c145dd4c/v1/get_capy_hour.go#L22

**Comment by Looskie** [comment]
Thank you for the support and issue! The way we do indexing for capys of the hour and capy of the day is a bit repetitive and i've been meaning to do a different way of gathering a stateless index. 

Contributions are welcomed! If I don't get to it by the time you are able to would appreciate your contribution very much ❤️

**Comment by Looskie** [comment]
sgould be fixed in #11 !
